# app/config/security.yml
security:
    encoders:
        FindBack\SiteBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [main, fb_provider]
        main:
            entity: { class: FindBackSiteBundle:User }
        fb_provider:
            id: facebook.user_provider

    firewalls:
        main:
            pattern:                   ^/
            form_login:
                provider:              main
                login_path:            /
                check_path:            /login_check
                default_target_path:   /
                username_parameter:    _username
                password_parameter:    _password
                csrf_parameter:        _csrf_token
                intention:             authenticate
                success_handler:       login.success_handler
            logout:
                path:                  /logout
                target:                /
                invalidate_session:    false # PHP Bug
                success_handler:       logout.success_handler
            fos_facebook:
                provider:              fb_provider
                app_url:               "http://apps.facebook.com/FindBack/"
                server_url:            "http://localhost/FindBack/web/app_dev.php"
                login_path:            /
                check_path:            /login_fb_check
            anonymous:                 true
            remember_me:
                key:                   "%secret%"
                lifetime:              31536000 # 365 jours en secondes
                path:                  /
                domain:                ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }