find_back_site_homepage:
    pattern:  /
    defaults: { _controller: FindBackSiteBundle:Base:index }

register_check:
    pattern:  /register_check
    defaults: { _controller: FindBackSiteBundle:Base:create }

login_check:
    pattern:  /login_check

#login_fb_check:
#    pattern:  /login_fb_check

logout:
    pattern:  /logout

account:
    pattern:  /me
    defaults: { _controller: FindBackSiteBundle:User:index }

account_edit:
    pattern:  /account/edit
    defaults: { _controller: FindBackSiteBundle:User:edit }

wanted:
    pattern:  /wanted
    defaults: { _controller: FindBackSiteBundle:Wanted:index }

wanted_publish:
    pattern:  /wanted/publish
    defaults: { _controller: FindBackSiteBundle:Wanted:publish }

wanted_check:
    pattern:  /wanted/check
    defaults: { _controller: FindBackSiteBundle:Wanted:check }

wanted_show:
    pattern:  /wanted/{id}/show
    defaults: { _controller: FindBackSiteBundle:Wanted:show }