parameters:
    login.success_handler.class: FindBack\SiteBundle\Handler\LoginSuccessHandler

services:
    login.success_handler:
        class: %login.success_handler.class%
        public: false
        arguments:  ['@router', '@doctrine.orm.entity_manager', '@service_container' ]