parameters:
#    find_back_site.example.class: FindBack\SiteBundle\Example

services:
#    find_back_site.example:
#        class: %find_back_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]