FindBack\SiteBundle\Entity\Date:
    type:  entity
    repositoryClass: FindBack\SiteBundle\Entity\DateRepository
    table: dates
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        date:
            type: string
        time:
            type: string
            nullable: true
    oneToMany:
        wanteds:
            targetEntity: Wanted
            mappedBy: date