FindBack\SiteBundle\Entity\Place:
    type:  entity
    repositoryClass: FindBack\SiteBundle\Entity\PlaceRepository
    table: places
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        formattedAddress:
            type: string
            length: 255
        city:
            type: string
            length: 60
        street:
            type: string
            length: 60
        location:
            type: string
            length: 255
        establishmentName:
            type: string
            length: 60
            nullable: true
        establishmentType:
            type: string
            length: 60
            nullable: true
    manyToMany:
        users:
            targetEntity: User
    oneToMany:
        wanteds:
             targetEntity: Wanted
             mappedBy: place