FindBack\SiteBundle\Entity\User:
    type:  entity
    repositoryClass: FindBack\SiteBundle\Entity\UserRepository
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        facebookId:
            type: string
            length: 255
            nullable: true
        birthdate:
            type: date
            nullable: true
        gender:
            type: string
            length: 255
            nullable: true
        salt:
            type: string
            length: 32
        isActive:
            type: boolean
        facebookPage:
            type: string
            length: 255
            nullable: true
        #facebookId:
        #    type: string
        #    length: 255
        #    nullable: true
    uniqueConstraints:
            email_idx:
                columns: email