FindBack\SiteBundle\Entity\User:
    type:  entity
    repositoryClass: FindBack\SiteBundle\Entity\UserRepository
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        facebookId:
            type: string
            length: 255
            nullable: true
        birthdate:
            type: date
            nullable: true
        gender:
            type: string
            length: 10
        salt:
            type: string
            length: 32
        isActive:
            type: boolean
        facebookPage:
            type: string
            length: 255
            nullable: true
        facebookId:
            type: string
            length: 255
            nullable: true
        website:
            type: string
            length: 255
            nullable: true
        found:
            type: integer
            length: 11
            nullable: true
        biography:
            type: text
            nullable: true
    oneToOne:
        description:
            targetEntity: Description
            joinColumn:
                name: description_id
                referencedColumnName: id
    manyToMany:
        places:
            targetEntity: Place
    oneToMany:
        wanteds:
            targetEntity: Wanted
            mappedBy: user